opam-version: "2.0"
synopsis: "Shared OCaml logic with native and web platform UIs"
maintainer: "Logseq <hello@logseq.com>"
authors: "Logseq"
license: "MIT"
homepage: "https://github.com/logseq/ocaml-demo"
bug-reports: "https://github.com/logseq/ocaml-demo/issues"
dev-repo: "git+https://github.com/logseq/ocaml-demo.git"
depends: [
  "ocaml" {>= "5.1.0"}
  "dune" {>= "3.17"}
  "melange"
  "datascript_ocaml"
  "datascript-ocaml-native"
  "datascript-ocaml-melange"
  "yojson" {with-test}
]
build: [
  ["dune" "subst"] {dev}
  [
    "dune"
    "build"
    "-p"
    name
    "-j"
    jobs
    "@install"
    "@runtest" {with-test}
  ]
]
pin-depends: [
  ["datascript_ocaml.dev" "git+https://github.com/logseq/datascript-ocaml.git#main"]
  ["datascript-ocaml-native.dev" "git+https://github.com/logseq/datascript-ocaml.git#main"]
  ["datascript-ocaml-melange.dev" "git+https://github.com/logseq/datascript-ocaml.git#main"]
  ["persistent_sorted_set_ocaml.dev" "git+https://github.com/logseq/persistent-sorted-set-ocaml.git#main"]
]
