(executable
 (name ocaml_demo_model_test)
 (libraries
  ocaml_demo_model
  datascript-ocaml-native
  datascript-ocaml-native.sqlite))

(rule
 (alias runtest)
 (deps ocaml_demo_model_test.exe)
 (action
  (run ./ocaml_demo_model_test.exe)))

(executable
 (name ocaml_demo_rpc_test)
 (libraries ocaml_demo_rpc datascript-ocaml-native yojson))

(rule
 (alias runtest)
 (deps ocaml_demo_rpc_test.exe)
 (action
  (run ./ocaml_demo_rpc_test.exe)))
